blog/urls.py
from django.conf.urls import url

from . import views

app_name = 'blog'
urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
    url(r'^(?P<article_id>[0-9]+)/like/$', views.like, name='like'),
]

blog_project/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from main import views as mainviews

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^blog/', include('blog.urls')),
    url(r'^$', mainviews.HomePageView.as_view(), name='index')
]

blog/models.py
import datetime

from django.db import models
from django.utils.encoding import python_2_unicode_compatible
from django.utils import timezone

# Create your models here.
class Article(models.Model):
    article_title_text = models.CharField(max_length=200)
    article_content = models.TextField()
    date_published = models.DateTimeField('date published')
    likes = models.IntegerField(default=0)
    def __str__(self):
        return self.article_title_text
    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.date_published <= now
    was_published_recently.admin_order_field = 'date_published'
    was_published_recently.boolean = True
    was_published_recently.short_description = 'Published recently?'

main/models.py
from django.db import models

# Create your models here.

class PageDescription(models.Model):
    page_description = models.TextField()
    display_on_page = models.CharField(max_length=200)
    def __str__(self):
        return self.page_description

blog/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.views import generic
from django.utils import timezone

from .models import Article
from main.models import PageDescription

# Create your views here.
class IndexView(generic.ListView):
    template_name = 'blog/index.html'
    context_object_name = 'latest_article_list'
    def get_context_data(self, **kwargs):
        context = super(IndexView, self).get_context_data(**kwargs)
        page_description = PageDescription.objects.filter(display_on_page="blog").first()
        if page_description is not None:
            context['page_description'] = page_description
        return context
    def get_queryset(self):
        """
        Return the last five published articles (not including those set to be
        published in the future).
        """
        return Article.objects.filter(
            date_published__lte=timezone.now()
        ).order_by('-date_published')[:5]

class DetailView(generic.DetailView):
    model = Article
    template_name = 'blog/detail.html'

    def get_queryset(self):
        """
        Excludes any articles that aren't published yet.
        """
        return Article.objects.filter(date_published__lte=timezone.now())

def like(request, article_id):
    article = get_object_or_404(Article, pk=article_id)
    try:
        article.likes += 1
        article.save()
    except (KeyError, Article.DoesNotExist):
        # Redisplay the article like form.
        return render(request, 'blog/detail.html', {
            'article': article,
            'error_message': "You didn't select like.",
        })
    else:
        # article.likes += 1
        # article.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('blog:detail', args=(article.id,)))

main/views.py
from django.shortcuts import render
from django.views.generic.base import TemplateView

from blog.models import Article
from main.models import PageDescription

# Create your views here.
class HomePageView(TemplateView):
    template_name = 'main/index.html'
    def get_context_data(self, **kwargs):
        context = super(HomePageView, self).get_context_data(**kwargs)
        context['latest_article'] = Article.objects.last()
        page_description = PageDescription.objects.filter(display_on_page="home").first()
        if page_description is not None:
            context['page_description'] = page_description
        return context

blog/templates/blog/detail.html
{% extends 'main/base.html' %}
{% block content %}

<h1>{{ article.article_title_text }}</h1>
<ul>
    <li>{{ article.article_content }}</li>
    <!-- <li>Likes: {{ article.likes }}</li> -->
</ul>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<!-- <form action="{% url 'blog:like' article.id %}" method="post">
  {% csrf_token %}
  <input type="radio" name="article" id="article{{ article.id }}" value="{{ article.id }}" />
  <label for="article{{ article.id }}">{{ article.article_content }}</label><br />
  <input type="submit" value="Like" class="small ui button"/>
</form> -->

{% endblock %}

blog/templates/blog/index.html
{% extends 'main/base.html' %}
{% block content %}

{% if latest_article_list %}
    <ul>
    {% for article in latest_article_list %}
        <li><a href="{% url 'blog:detail' article.id %}">{{ article.article_title_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No articles are available.</p>
{% endif %}

{% endblock %}

main/templates/main/base.html
<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Rakstu vācele</title>
  {% load static %}
  <link rel="stylesheet" type="text/css" href="{% static 'blog/style.css' %}" />
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/semantic-ui/2.2.10/semantic.min.css">
  <script src="https://cdn.jsdelivr.net/semantic-ui/2.2.10/semantic.min.js"></script>
</head>

<body class="ui container">
  <div class="ui menu ">
    <a href="{% url 'index' %}" class="item">Sākums</a>
    <a href="{% url 'blog:index' %}" class="item">Neregulāri raksti</a>
    <a href="http://dok.rudenspavasaris.id.lv/" class="item right">Dokumentācija</a>
  </div>

  <div class="body-content">
    <p>
      {{ page_description }}
    </p>
    {% block content %}{% endblock %}
  </div>

  {% block scripts %}{% endblock %}

</body>

</html>

main/templates/main/index.html
{% extends 'main/base.html' %}
{% block content %}

{% if latest_article.id %}
<h3>
  <a href="{% url 'blog:detail' latest_article.id %}">{{ latest_article.article_title_text }}</a>
</h3>

<ul>
    <li>{{ latest_article.article_content }}</li>
</ul>
{% endif %}

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

{% endblock %}